export type ExternalReferralPlatform = "小红书" | "牛客" | "力扣";

export type ExternalReferralSourceRecord = {
  id: string;
  company_name: string;
  code: string;
  applicable_roles: string;
  usage_note: string;
  source_platform: ExternalReferralPlatform;
  source_url: string;
  published_at: string | null;
  source_verified_at: string;
};

const VERIFIED_AT = "2026-09-01T00:00:00.000Z";

function source(input: Omit<ExternalReferralSourceRecord, "source_verified_at">): ExternalReferralSourceRecord {
  return { ...input, source_verified_at: VERIFIED_AT };
}

/**
 * Manually curated public referral codes. Every row has an inspectable source
 * URL and was accepted only when the source explicitly names the 2027/27
 * campus or autumn-hiring batch and prints a code in text or an unambiguous
 * poster. These rows stay virtual and never become a fake Supabase user post.
 */
export const EXTERNAL_REFERRAL_SOURCES: ExternalReferralSourceRecord[] = [
  source({
    id: "xiaohongshu-tencent-oop3fb5j",
    company_name: "腾讯",
    code: "OOP3FB5J",
    applicable_roles: "腾讯 27 届校招技术、产品、市场、设计、职能等岗位",
    usage_note: "小红书公开帖子标题和海报明确写出“腾讯校招27内推码 OOP3FB5J”；使用前请在腾讯官方投递页核对。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a8c212d000000002b00102f",
    published_at: "2026-08-24",
  }),
  source({
    id: "xiaohongshu-lixin-evkm3j",
    company_name: "立信",
    code: "EVKM3J",
    applicable_roles: "立信 2027 校招审计、IT 审计、税务、咨询、评估等岗位",
    usage_note: "小红书公开帖子正文明确面向 2027 届秋招，并给出网申内推码 EVKM3J；使用前请核对官方网申状态。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a95054c000000002c03cf59",
    published_at: "2026-08-31",
  }),
  source({
    id: "xiaohongshu-lixin-evkm3s",
    company_name: "立信",
    code: "EVKM3S",
    applicable_roles: "立信 2027 届秋招审计、IT 审计、税务、咨询、评估等岗位",
    usage_note: "小红书公开帖子标题标注 2027 立信校招，海报明确显示推荐码 EVKM3S；使用前请核对官方网申状态。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a90f4e40000000020035f9d",
    published_at: "2026-08-29",
  }),
  source({
    id: "xiaohongshu-lixin-evvm3h",
    company_name: "立信",
    code: "EVVM3H",
    applicable_roles: "立信 BDO 2027 秋招岗位",
    usage_note: "小红书公开搜索结果标题明确写出“立信 BDO 2027 秋招｜内推码 EVVM3H”；使用前请核对官方网申状态。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a95390b000000002c03f18e",
    published_at: "2026-08-31",
  }),
  source({
    id: "xiaohongshu-netease-shqaig",
    company_name: "网易互娱",
    code: "shqAig",
    applicable_roles: "网易互娱 27 届秋招技术、策划、美术、测试、运营等岗位",
    usage_note: "小红书公开帖子正文列出网易互娱 27 届秋招内推码 shqAig，并附官方岗位链接；使用前请在官方页面核对。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a910de200000000260368f7",
    published_at: "2026-08-29",
  }),
  source({
    id: "xiaohongshu-sany-evvm20",
    company_name: "三一集团",
    code: "EVVM20",
    applicable_roles: "三一集团 27 届校招研发、算法、产品、职能等岗位",
    usage_note: "小红书公开帖子标题明确写出三一 27 届校招和 EVVM20 内推码；使用前请核对官方投递入口。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a8eae4f00000000260008ae",
    published_at: "2026-08-27",
  }),
  source({
    id: "xiaohongshu-sany-esvmbj",
    company_name: "三一集团",
    code: "ESVMBJ",
    applicable_roles: "三一集团 27 届秋招正式批研发、算法、产品、职能等岗位",
    usage_note: "小红书公开搜索结果多条 27 秋招帖子重复标注 ESVMBJ，来源帖子显示为校园大使码；使用前请核对官方投递入口。",
    source_platform: "小红书",
    source_url: "https://www.xiaohongshu.com/explore/6a8fc1b7000000002903c29f",
    published_at: "2026-08-29",
  }),
  source({
    id: "nowcoder-changyou-ntacc5l",
    company_name: "搜狐畅游",
    code: "NTAcC5L",
    applicable_roles: "搜狐畅游 2027 秋招提前批游戏策划、开发、美术、运营、测试、平台与职能岗位",
    usage_note: "牛客公开帖子明确面向 27 届毕业生，并附搜狐畅游官方投递入口与内推码 NTAcC5L。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/58b412c694994b248e17fa71b8c2acc9",
    published_at: null,
  }),
  source({
    id: "nowcoder-hypergryph-ntacuvq",
    company_name: "鹰角",
    code: "NTAcuvq",
    applicable_roles: "鹰角网络 2027 秋招游戏客户端、服务端、Java、SRE、AI 算法、引擎与技术美术岗位",
    usage_note: "牛客公开帖子明确写出鹰角网络 2027 秋招正式岗位、官方投递页和内推码 NTAcuvq。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/902d581c0bae45f28d97be02879be6ee",
    published_at: "2026-08-24",
  }),
  source({
    id: "nowcoder-ninebot-dsw45ddp",
    company_name: "九号公司",
    code: "DSw45DdP",
    applicable_roles: "九号公司 2027 秋招技术研发、设计、供应链、产品、营销、质量与职能岗位",
    usage_note: "牛客公开帖子明确标注九号公司 2027 届秋招和官方推荐码 DSw45DdP。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/2ea0b4e13bc146bfa5d98a10b2a465ab",
    published_at: "2026-08-27",
  }),
  source({
    id: "nowcoder-pdd-eq2cmrrfvw",
    company_name: "拼多多",
    code: "Eq2CmRRFVw",
    applicable_roles: "拼多多 2027 届云弧计划 AI Infra 研发工程师",
    usage_note: "牛客公开帖子列出拼多多 2027 届云弧计划岗位及对应内推码 Eq2CmRRFVw。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/0b57ed56251c4b3e9903229a490cef00",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-nqmdxemp8v",
    company_name: "拼多多",
    code: "nqMDxEMp8V",
    applicable_roles: "拼多多 2027 届云弧计划大模型算法工程师",
    usage_note: "牛客公开帖子列出拼多多 2027 届云弧计划岗位及对应内推码 nqMDxEMp8V。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/0b57ed56251c4b3e9903229a490cef00",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-ivj5fbtpqj",
    company_name: "拼多多",
    code: "IVj5fbTpQj",
    applicable_roles: "拼多多 2027 届商业化团队服务端研发工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出服务端研发内推码 IVj5fbTpQj。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-at2mse2ymi",
    company_name: "拼多多",
    code: "At2mse2YMI",
    applicable_roles: "拼多多 2027 届云弧计划 AI Infra 研发工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出 AI Infra 内推码 At2mse2YMI。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-rmk7szgix4",
    company_name: "拼多多",
    code: "rMk7SZGix4",
    applicable_roles: "拼多多 2027 届云弧计划大模型算法工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出大模型算法内推码 rMk7SZGix4。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-i6zmm9sgd4",
    company_name: "拼多多",
    code: "i6ZMM9SGD4",
    applicable_roles: "拼多多 2027 届 AI Agent 研发工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出 AI Agent 研发内推码 i6ZMM9SGD4。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-kfqijwvq6k",
    company_name: "拼多多",
    code: "KfQIjWVQ6K",
    applicable_roles: "拼多多 2027 届算法工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出算法工程师内推码 KfQIjWVQ6K。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-9qiuwijtyj",
    company_name: "拼多多",
    code: "9QiUWIjtYJ",
    applicable_roles: "拼多多 2027 届客户端研发工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出客户端研发内推码 9QiUWIjtYJ。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-pitdhpxsgr",
    company_name: "拼多多",
    code: "PITdhPXsgr",
    applicable_roles: "拼多多 2027 届 Web 前端研发工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出 Web 前端研发内推码 PITdhPXsgr。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-spvc8yu9hb",
    company_name: "拼多多",
    code: "sPvc8Yu9hb",
    applicable_roles: "拼多多 2027 届数据分析师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出数据分析师内推码 sPvc8Yu9hb。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "nowcoder-pdd-ccfia26d9k",
    company_name: "拼多多",
    code: "ccfiA26D9k",
    applicable_roles: "拼多多 2027 届安全工程师",
    usage_note: "牛客公开帖子明确标注 27 届校招提前批并列出安全工程师内推码 ccfiA26D9k。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/e46079ef0e3f4ebf9f5a82a77ffd0864",
    published_at: null,
  }),
  source({
    id: "leetcode-boke-71gpkxd",
    company_name: "波克游戏",
    code: "71GPKXD",
    applicable_roles: "波克游戏 2027 秋招研发、运营、策划、美术、职能岗位",
    usage_note: "力扣公开帖子明确标注波克 2027 秋招内推启动，并给出官方投递链接和内推码 71GPKXD。",
    source_platform: "力扣",
    source_url: "https://leetcode.cn/discuss/post/4013483/bo-ke-4399-27jie-qiu-zhao-nei-tui-qi-don-ig1n/",
    published_at: null,
  }),
  source({
    id: "leetcode-4399-9ueia",
    company_name: "4399",
    code: "9ueia",
    applicable_roles: "4399 2027 秋招产品、技术、美术、运营市场与职能岗位",
    usage_note: "力扣公开帖子明确标注 4399 游戏 2027 届校招并给出内推码 9ueia；使用前请核对官方投递页。",
    source_platform: "力扣",
    source_url: "https://leetcode.cn/discuss/post/4013483/bo-ke-4399-27jie-qiu-zhao-nei-tui-qi-don-ig1n/",
    published_at: null,
  }),
  source({
    id: "nowcoder-yuanrong-ntaw9fw",
    company_name: "元戎启行",
    code: "NTAW9FW",
    applicable_roles: "元戎启行 2027 届秋招算法、软件、系统评测、产品、项目与运营岗位",
    usage_note: "牛客公开帖子明确写出元戎启行 2027 届秋招投递链接和内推码 NTAW9FW。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/941db57e78e541b7aa525f7eceaa64e0",
    published_at: null,
  }),
  source({
    id: "nowcoder-yuanrong-ntaw61d",
    company_name: "元戎启行",
    code: "NTAW61d",
    applicable_roles: "元戎启行 27 届秋招算法、研发、产品与职能岗位",
    usage_note: "牛客公开帖子明确面向 27 届秋招并给出元戎启行内推码 NTAW61d；使用前请在官方页面核对。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/4b443e3c476e4f40a98ed714e49f49f6",
    published_at: null,
  }),
  source({
    id: "nowcoder-zhuoyu-ez3aa2",
    company_name: "卓驭",
    code: "EZ3AA2",
    applicable_roles: "卓驭 2027 届校园招聘算法、软件、嵌入式、测试、安全与非研发岗位",
    usage_note: "牛客公开帖子明确标注卓驭 27 届校招与推荐码 EZ3AA2。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/b725bb21b14f42dc82e16d03e8aca785",
    published_at: null,
  }),
  source({
    id: "nowcoder-zhuoyu-iz3a3j",
    company_name: "卓驭",
    code: "IZ3A3J",
    applicable_roles: "卓驭 2027 届秋招算法、研发、产品与职能岗位",
    usage_note: "牛客公开帖子明确标注卓驭科技 2027 秋招和推荐码 IZ3A3J。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/9f1a55389df54326bc5524c99ac60bdd",
    published_at: null,
  }),
  source({
    id: "nowcoder-nio-kzv2bgp",
    company_name: "蔚来",
    code: "KZV2BGP",
    applicable_roles: "蔚来 2027 届校招研发、算法、产品、数据、安全与职能岗位",
    usage_note: "牛客公开帖子明确写出蔚来 2027 届校招正式启动与内推码 KZV2BGP。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/98d2257456564fd49744056b60baf669",
    published_at: null,
  }),
  source({
    id: "nowcoder-ctyun-lgyzmp",
    company_name: "中国电信天翼云",
    code: "lgyzmp",
    applicable_roles: "天翼云 2027 届校招后端、大数据、测试、产品、解决方案、项目与算法岗位",
    usage_note: "牛客公开帖子明确标注天翼云 2027 届校招秋招、官方投递地址和内推码 lgyzmp。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/2618e8e55aac45c280f95d95879994eb",
    published_at: null,
  }),
  source({
    id: "nowcoder-keyence-eskjjr",
    company_name: "基恩士",
    code: "ESKJJR",
    applicable_roles: "基恩士 2027 秋招销售工程师、销售岗位",
    usage_note: "牛客公开帖子明确标注基恩士 2027 秋招网申与推荐码 ESKJJR。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/d6eb6e5b3f70447b8e9e51b970994290",
    published_at: null,
  }),
  source({
    id: "nowcoder-keyence-evkjvs",
    company_name: "基恩士",
    code: "EVKJVS",
    applicable_roles: "基恩士 2027 届秋招销售工程师、销售岗位",
    usage_note: "牛客公开帖子明确标注基恩士中国 2027 届秋招和校园大使推荐码 EVKJVS。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/2c9922e091e843c29e402637c557532b",
    published_at: null,
  }),
  source({
    id: "nowcoder-dji-dskerdhz",
    company_name: "大疆",
    code: "DSKeRdhz",
    applicable_roles: "大疆 27 届校招飞行器、算法、芯片、机械、硬件、软件、产品与测试岗位",
    usage_note: "牛客公开汇总明确标注大疆 27 届专属推荐码 DSKeRdhz，并附官方投递入口。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/a3f90b495a074aea9db7abbb9504e365",
    published_at: null,
  }),
  source({
    id: "nowcoder-netease-hpyu1u",
    company_name: "网易互娱",
    code: "HPyu1u",
    applicable_roles: "网易互娱 2027 届秋招技术、策划、美术、测试、运营等岗位",
    usage_note: "牛客公开帖子明确面向 27 届秋招所有岗位，并给出内推码 HPyu1u。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/2a86985ef1804f5b97c3cb4d44287158",
    published_at: null,
  }),
  source({
    id: "nowcoder-netease-xvz8lnr",
    company_name: "网易互娱",
    code: "XVZ8LnR",
    applicable_roles: "网易互娱 2027 届秋招策划、程序、美术、测试、运营、AI 与产品岗位",
    usage_note: "牛客公开帖子明确标注网易游戏互娱 2027 届秋招正式开启、适用毕业时间和内推码 XVZ8LnR。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/799af271d14948e5af5a266bc4e0b1a4",
    published_at: null,
  }),
  source({
    id: "nowcoder-mihoyo-r92sd",
    company_name: "米哈游",
    code: "R92SD",
    applicable_roles: "米哈游 27 届秋招程序、产品策划、美术、质控、运营、市场与综合岗位",
    usage_note: "牛客公开帖子标注米哈游 27 届秋招正式批，并给出内推码 R92SD；使用前请在米哈游官方页面核对。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/c460b3b85b51461c819df2af967ddbef",
    published_at: null,
  }),
  source({
    id: "nowcoder-pony-ukguhfq",
    company_name: "小马智行",
    code: "UKGUHFQ",
    applicable_roles: "小马智行 2027 届校园招聘算法、软件、测试与硬件岗位",
    usage_note: "牛客公开帖子明确面向小马智行 2027 届校园招聘并给出内推码 UKGUHFQ；使用前请核对官方投递页。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/6c8928d5171f4070a66b6066e128d257",
    published_at: null,
  }),
  source({
    id: "nowcoder-xiaomi-qn8kf6z",
    company_name: "小米",
    code: "QN8KF6Z",
    applicable_roles: "小米 2027 届秋招软件、算法、硬件、芯片、产品、运营与职能岗位",
    usage_note: "牛客公开帖子明确标注小米 2027 届校招正式开启、毕业时间与内推码 QN8KF6Z。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/d7bb128e28a44889810599505012da29",
    published_at: null,
  }),
  source({
    id: "nowcoder-xiaomi-4f3hwd7",
    company_name: "小米",
    code: "4F3HWD7",
    applicable_roles: "小米 2027 届全球校园招聘 AI、软件、硬件、芯片、汽车、产品与职能岗位",
    usage_note: "牛客公开帖子明确标注小米集团 2027 届全球校园招聘与内推码 4F3HWD7。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/0a0c0cf3e9274f38bf2c2aeb347397ee",
    published_at: null,
  }),
  source({
    id: "nowcoder-xiaomi-k47b7n7",
    company_name: "小米",
    code: "K47B7N7",
    applicable_roles: "小米 2027 届秋招软件、算法、产品、运营与职能岗位",
    usage_note: "牛客公开帖子明确标注小米 2027 届秋季校园招聘和专属内推码 K47B7N7。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/795d9f8c2f674fbca5beb1134640276d",
    published_at: null,
  }),
  source({
    id: "nowcoder-xiaomi-xc8bfx8",
    company_name: "小米",
    code: "XC8BFX8",
    applicable_roles: "小米 27 届秋招软件、算法、芯片、汽车、机器人、产品与职能岗位",
    usage_note: "牛客公开帖子明确标注小米 27 届秋招已开启并给出大使推荐码 XC8BFX8。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/discuss/922115090302636032",
    published_at: null,
  }),
  source({
    id: "nowcoder-xiaomi-qdr2m92",
    company_name: "小米",
    code: "QDR2M92",
    applicable_roles: "小米 2027 届全球校园招聘 AI、大模型、软硬件、汽车、供应链、产品与设计岗位",
    usage_note: "牛客公开帖子明确标注小米 2027 届全球校园招聘和内推码 QDR2M92。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/feed/main/detail/491438cd7eb54725845c021e2364c627",
    published_at: null,
  }),
  source({
    id: "nowcoder-tencent-tecced77z1",
    company_name: "腾讯",
    code: "TECCED77Z1",
    applicable_roles: "腾讯 2027 届校招产品、技术、市场、设计与职能岗位",
    usage_note: "牛客公开帖子明确面向腾讯 2027 届校招，并给出内推码 TECCED77Z1；腾讯音乐与腾讯集团码不可混用。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/discuss/919906064571592704",
    published_at: null,
  }),
  source({
    id: "nowcoder-tme-ds0eg-nuv",
    company_name: "腾讯音乐",
    code: "DS0EGNUV",
    applicable_roles: "腾讯音乐 2027 届秋招技术、产品、设计、内容、市场与专业岗位",
    usage_note: "牛客公开帖子明确标注腾讯音乐 2027 届秋招，并特别说明其内推码与腾讯集团不通用：DS0EGNUV。",
    source_platform: "牛客",
    source_url: "https://www.nowcoder.com/discuss/920018058939224064",
    published_at: null,
  }),
];

export function buildExternalReferralRows(companyNames: Iterable<string>, verifiedAt = VERIFIED_AT) {
  const allowed = new Set([...companyNames].map((name) => String(name).trim()).filter(Boolean));
  return EXTERNAL_REFERRAL_SOURCES
    .filter((record) => allowed.has(record.company_name))
    .map((record) => ({
      id: `external-referral-${record.id}`,
      company_name: record.company_name,
      job_id: null,
      applicable_roles: record.applicable_roles,
      code: record.code,
      usage_note: `${record.usage_note} 来源：${record.source_platform}，核验于 ${verifiedAt.slice(0, 10)}。`,
      expires_at: null,
      created_at: record.published_at ? `${record.published_at}T00:00:00.000Z` : verifiedAt,
      updated_at: verifiedAt,
      source_type: "public_post" as const,
      source_job_ids: [] as string[],
      source_urls: [record.source_url],
      source_platform: record.source_platform,
      source_url: record.source_url,
      published_at: record.published_at,
      source_verified_at: verifiedAt,
    }));
}
