-- Generated from data/source/27秋招信息整理.xlsx.
-- Valid rows: 167. Skipped rows: 2.

insert into public.jobs (
  company_name,
  start_date,
  industry,
  batch_type,
  job_titles,
  locations,
  apply_url,
  notes,
  logo_url,
  tags,
  is_active
)
select *
from (
values
('中茵微', '7.2', '科技', '27秋招正式批', '硬件工程类', '北京 上海 成都 苏州 南京', 'https://mp.weixin.qq.com/s/I7gv6zdyB0XGQpAiNm_zQQ', null, null, array['科技', '27秋招正式批', '北京', '上海', '成都', '苏州', '南京', '硬件工程类']::text[], true),
('杰华特', '7.1', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 产品类', '杭州 成都', 'https://joulwatt.zhiye.com/campus/jobs', null, null, array['科技', '27秋招正式批', '杭州', '成都', '软件研发类', '硬件工程类', '产品类']::text[], true),
('微步在线', '6.30', '互联网', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 运营类, 产品类, 销售类', '北京 上海 深圳 杭州 济南', 'https://app.mokahr.com/campus-recruitment/threatbook/39679?locale=zh-CN#/', null, null, array['互联网', '27秋招正式批', '北京', '上海', '深圳', '杭州', '济南', '软件研发类', '市场类（包含商分', '战略）', '运营类', '产品类', '销售类']::text[], true),
('高德红外', '6.17', '科技', '27秋招正式批', '硬件工程类', '武汉 无锡', 'https://gdhw.zhiye.com/campus', null, null, array['科技', '27秋招正式批', '武汉', '无锡', '硬件工程类']::text[], true),
('泛微', '7.1', '科技', '27秋招提前批', '销售类', '上海 郑州', 'https://jsj.top/f/nvVv4H?x_field_1=%E9%BB%84%E5%AE%87%E8%88%AA', null, null, array['科技', '27秋招提前批', '上海', '郑州', '销售类']::text[], true),
('RoboSense', '7.1', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 产品类', '上海 深圳', 'https://mp.weixin.qq.com/s/eZKjE-4QXcTyxvcuDUe2oQ', null, null, array['科技', '27秋招提前批', '上海', '深圳', '软件研发类', '硬件工程类', '产品类']::text[], true),
('百度', '7.1', '互联网', '27秋招提前批', '管培生', '北京', 'https://talent.baidu.com/jobs/list', null, null, array['互联网', '27秋招提前批', '北京', '管培生']::text[], true),
('普源精电', '7.1', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 管培生, 财务类', '北京 上海 苏州 西安', 'https://rigolportal.jobs.feishu.cn/campus/position/list', null, null, array['科技', '27秋招正式批', '北京', '上海', '苏州', '西安', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '管培生', '财务类']::text[], true),
('锐石创芯', '7.1', '科技', '27秋招正式批', '硬件工程类, 生产制造类, 财务类', '上海 深圳 西安 成都 重庆', 'https://mp.weixin.qq.com/s/TPNBtkUgKHKzErVaZFgWKA', null, null, array['科技', '27秋招正式批', '上海', '深圳', '西安', '成都', '重庆', '硬件工程类', '生产制造类', '财务类']::text[], true),
('思瑞浦', '7.1', '科技', '27秋招正式批', '硬件工程类, 销售类', '全国', 'https://app.mokahr.com/campus-recruitment/3peakic/67894#/page/%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98', null, null, array['科技', '27秋招正式批', '全国', '硬件工程类', '销售类']::text[], true),
('乐鑫科技', '7.1', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 销售类, 人力类', '上海 深圳 苏州 新加坡', 'https://www.espressif.com.cn/zh-hans/join-us/job-search?title=&sessionid=&field_job_classification_tid%5B0%5D=2575&field_job_classification_tid%5B1%5D=2577&field_job_classification_tid%5B2%5D=2573', null, null, array['科技', '27秋招正式批', '上海', '深圳', '苏州', '新加坡', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '销售类', '人力类']::text[], true),
('方正微', '6.29', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 销售类, 生产制造类, 财务类', '深圳', 'https://founderic.zhiye.com/campus/jobs', null, null, array['科技', '27秋招正式批', '深圳', '软件研发类', '硬件工程类', '销售类', '生产制造类', '财务类']::text[], true),
('多益网络', '7.1', '互联网, 游戏', '27秋招提前批', '软件研发类, 设计类, 运营类, 产品类, 人力类, 财务类', '广州 武汉 杭州', 'https://mp.weixin.qq.com/s/EFBgiZwEfmS9P6Ldvk2dXA', null, null, array['互联网', '游戏', '27秋招提前批', '广州', '武汉', '杭州', '软件研发类', '设计类', '运营类', '产品类', '人力类', '财务类']::text[], true),
('京东（tet）', '7.1', '互联网', '27秋招提前批', '软件研发类, 产品类, 运营类, 管培生', '北京 宿迁等', 'https://campus.jd.com/home#/jobs?to=present&type=present', null, null, array['互联网', '27秋招提前批', '北京', '宿迁等', '软件研发类', '产品类', '运营类', '管培生']::text[], true),
('华芯天微', '7.1', '科技', '27秋招正式批', '软件研发类, 硬件工程类', '成都', 'https://mp.weixin.qq.com/s/cZ3llBGB-5cYsdUgNzd3Tw', null, null, array['科技', '27秋招正式批', '成都', '软件研发类', '硬件工程类']::text[], true),
('诺亚控股', '6.24', '金融', '27秋招提前批', '其他, 销售类, 管培生', '香港', 'https://mp.weixin.qq.com/s/KLmrx-mrAFuyEq8oRNfy1g?scene=1&click_id=1504', null, null, array['金融', '27秋招提前批', '香港', '其他', '销售类', '管培生']::text[], true),
('中科光电', '6.30', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '合肥', 'https://app.mokahr.com/campus-recruitment/hdzn/151324?locale=zh-CN#/jobs?zhineng%5B0%5D=209066', null, null, array['科技', '27秋招提前批', '合肥', '软件研发类', '硬件工程类']::text[], true),
('京东方', '6.30', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 产品类, 管培生', '北京 烟台 南京 合肥 福州', 'https://campus.boe.com/custom/campus', null, null, array['科技', '27秋招提前批', '北京', '烟台', '南京', '合肥', '福州', '软件研发类', '硬件工程类', '产品类', '管培生']::text[], true),
('内蒙古农商银行', '6.29', '金融', '27秋招正式批', '管培生, 其他', '内蒙古', 'https://nmnshxy2026.hersingdat.com/', null, null, array['金融', '27秋招正式批', '内蒙古', '管培生', '其他']::text[], true),
('科大讯飞', '6.30', '互联网', '27秋招提前批', '软件研发类, 市场类（包含商分 战略）, 产品类', '合肥', 'https://mp.weixin.qq.com/s/OEW0DyGsAZUxlUtEWfUwvQ', null, null, array['互联网', '27秋招提前批', '合肥', '软件研发类', '市场类（包含商分', '战略）', '产品类']::text[], true),
('开立医疗', '6.29', '其他', '27秋招正式批', '财务类, 软件研发类, 硬件工程类', '深圳', 'https://app.mokahr.com/campus-recruitment/sonoscape/94392/#/', null, null, array['其他', '27秋招正式批', '深圳', '财务类', '软件研发类', '硬件工程类']::text[], true),
('新和成', '6.29', '制造业', '27秋招正式批', '销售类, 生产制造类', '山东 天津 浙江', 'https://xinhecheng1.zhiye.com/campus/jobs?2=%5B%7B%22id%22%3A%2215%22%2C%22label%22%3A%22%E5%B1%B1%E4%B8%9C%26%E5%A4%A9%E6%B4%A5%22%7D%5D', null, null, array['制造业', '27秋招正式批', '山东', '天津', '浙江', '销售类', '生产制造类']::text[], true),
('镭目科技', '6.29', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 销售类, 人力类, 管培生', '北京 长沙 衡阳', 'https://mp.weixin.qq.com/s/zLiUEigJl1iApPnE6EpBDw?scene=1&click_id=1344', null, null, array['科技', '27秋招正式批', '北京', '长沙', '衡阳', '软件研发类', '硬件工程类', '销售类', '人力类', '管培生']::text[], true),
('穹彻智能（人才计划）', '6.29', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '上海', 'https://mp.weixin.qq.com/s/LR6BvAhbjuMPc4GtYQGkug?scene=1', null, null, array['科技', '27秋招提前批', '上海', '软件研发类', '硬件工程类']::text[], true),
('中兴通讯', '6.26', '央国企', '27秋招提前批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 产品类, 销售类', '全国', 'https://app.mokahr.com/campus-recruitment/zte/46903#/jobs?project=100120257', null, null, array['央国企', '27秋招提前批', '全国', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '产品类', '销售类']::text[], true),
('乐元素', '6.2', '互联网, 游戏', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 设计类, 运营类, 产品类', '北京 上海', 'https://app.mokahr.com/campus-recruitment/leyuansu/166186#/jobs?340045%5B0%5D=%E5%BA%94%E5%B1%8A%E7%94%9F&page=1&anchorName=jobsList', null, null, array['互联网', '游戏', '27秋招正式批', '北京', '上海', '软件研发类', '市场类（包含商分', '战略）', '设计类', '运营类', '产品类']::text[], true),
('长飞光纤', '6.26', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 产品类, 销售类', '武汉', 'https://yofc2.zhiye.com/campus/jobs', null, null, array['科技', '27秋招正式批', '武汉', '软件研发类', '硬件工程类', '产品类', '销售类']::text[], true),
('杭州新中大', '6.26', '科技', '27秋招正式批', '软件研发类, 产品类, 运营类, 市场类（包含商分 战略）, 销售类, 财务类', '杭州', 'https://mp.weixin.qq.com/s/OD0N30qrrUgW-9UspxjnsA?scene=1&click_id=1278', null, null, array['科技', '27秋招正式批', '杭州', '软件研发类', '产品类', '运营类', '市场类（包含商分', '战略）', '销售类', '财务类']::text[], true),
('必易微', '6.26', '科技', '27秋招正式批', '软件研发类, 硬件工程类', '上海 深圳 杭州 成都 厦门 珠海', 'https://mp.weixin.qq.com/s/KM8M5MLyPnkMNWhc3MuQ3g?scene=1&click_id=1277', null, null, array['科技', '27秋招正式批', '上海', '深圳', '杭州', '成都', '厦门', '珠海', '软件研发类', '硬件工程类']::text[], true),
('掌趣科技', '6.25', '互联网', '27秋招提前批', '人力类', '北京', 'https://app.mokahr.com/campus-recruitment/ourpalm/43628#/job/0289ff68-d764-4c22-bfe7-f368cbbb2263', null, null, array['互联网', '27秋招提前批', '北京', '人力类']::text[], true),
('科华集团', '6.26', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 产品类, 管培生', '深圳 厦门', 'https://app.mokahr.com/campus-recruitment/kehua/92510#/page/%E6%A0%A1%E6%8B%9B%E8%81%8C%E4%BD%8D', null, null, array['科技', '27秋招提前批', '深圳', '厦门', '软件研发类', '硬件工程类', '产品类', '管培生']::text[], true),
('中国电信天翼云', '6.26', '央国企', '27秋招正式批', '软件研发类, 硬件工程类, 产品类', '北京 上海 广州 成都 厦门', 'https://wecruit.hotjob.cn/SU62b2ae672f9d24458d72f9cc/pb/school.html', null, null, array['央国企', '27秋招正式批', '北京', '上海', '广州', '成都', '厦门', '软件研发类', '硬件工程类', '产品类']::text[], true),
('小马智行（人才计划）', '6.26', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '北京 上海 广州', 'https://ponyai.jobs.feishu.cn/ponycampus', null, null, array['科技', '27秋招提前批', '北京', '上海', '广州', '软件研发类', '硬件工程类']::text[], true),
('航天科技集团', '6.26', '央国企', '27秋招提前批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 设计类, 运营类, 产品类, 生产制造类, 销售类, 人力类, 设计类, 职能类, 财务类', '全国', 'https://mp.weixin.qq.com/s/z3LM4t-hkE0QJj_YXBilUw?scene=1&click_id=1225', null, null, array['央国企', '27秋招提前批', '全国', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '设计类', '运营类', '产品类', '生产制造类', '销售类', '人力类', '职能类', '财务类']::text[], true),
('联合飞机', '6.26', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 人力类, 职能类', '全国', 'https://mp.weixin.qq.com/s/7L_3_kHppSb4si2x1aYP0Q?scene=1&click_id=1199', null, null, array['科技', '27秋招提前批', '全国', '软件研发类', '硬件工程类', '人力类', '职能类']::text[], true),
('能良电商', '6.23', '互联网', '27秋招正式批', '运营类, 人力类, 财务类, 软件研发类', '上海 北京 深圳 郑州 济南 武汉', 'https://mp.weixin.qq.com/s/LYM7hdZ9iW3tMA9uZffCEw', null, null, array['互联网', '27秋招正式批', '上海', '北京', '深圳', '郑州', '济南', '武汉', '运营类', '人力类', '财务类', '软件研发类']::text[], true),
('中核—中国中原对外工程有限公司', '5.18', '央国企', '27秋招正式批', '生产制造类, 职能类', '北京 海外', 'https://cnnc.m.zhiye.com/joblist.html?jc=2&ky=&pi=1&ps=10&c1=&c2=1_162&c=', null, null, array['央国企', '27秋招正式批', '北京', '海外', '生产制造类', '职能类']::text[], true),
('中建八局集团', '6.25', '央国企', '27秋招正式批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 设计类, 运营类, 产品类, 销售类, 生产制造类, 管培生, 设计类, 人力类, 职能类, 财务类, 教师, 咨询, 其他', '全国', 'https://job.cscec8b.com.cn/campus', '中建八局旗下公司 一公司 二公司等数十家 除集团总部外27校招全面启动', null, array['央国企', '27秋招正式批', '全国', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '设计类', '运营类', '产品类', '销售类', '生产制造类', '管培生', '人力类', '职能类', '财务类', '教师', '咨询']::text[], true),
('联发科技', '6.25', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '北京 上海 深圳 武汉 成都 合肥', 'https://mediatek.zhiye.com/campus', null, null, array['科技', '27秋招提前批', '北京', '上海', '深圳', '武汉', '成都', '合肥', '软件研发类', '硬件工程类']::text[], true),
('大疆', '6.25', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 产品类', '北京 上海 深圳', 'https://apply.careers.dji.com/campus-recruitment/dji/143359?locale=zh-CN#/?page=1&pageSize=30', null, null, array['科技', '27秋招正式批', '北京', '上海', '深圳', '软件研发类', '硬件工程类', '产品类']::text[], true),
('欧普照明', '5.28', '快消', '27秋招提前批', '管培生, 人力类', '上海', 'https://wecruit.hotjob.cn/SU646ed9920dcad45af14821b4/mc/position/campus', null, null, array['快消', '27秋招提前批', '上海', '管培生', '人力类']::text[], true),
('新凯来', '6.25', '央国企', '27秋招正式批', '软件研发类, 硬件工程类, 销售类, 人力类, 财务类, 职能类', '全国', 'https://mp.weixin.qq.com/s/LCZtpuXbu6uumZmNFg7AZA?scene=1', null, null, array['央国企', '27秋招正式批', '全国', '软件研发类', '硬件工程类', '销售类', '人力类', '财务类', '职能类']::text[], true),
('固胜科技', '6.18', '科技', '27秋招正式批', '软件研发类, 产品类, 销售类, 财务类, 设计类, 生产制造类, 管培生, 市场类（包含商分 战略）', '深圳 武汉', 'https://mp.weixin.qq.com/s/zuap56bn_5aTm3FuZ1Rg5w', null, null, array['科技', '27秋招正式批', '深圳', '武汉', '软件研发类', '产品类', '销售类', '财务类', '设计类', '生产制造类', '管培生', '市场类（包含商分', '战略）']::text[], true),
('中国航天科工', '6.24', '央国企', '27秋招正式批', '软件研发类, 硬件工程类, 产品类, 生产制造类, 财务类, 其他', '全国', 'https://mp.weixin.qq.com/s/yTLw8hN6GF26vSZy8zekEw', null, null, array['央国企', '27秋招正式批', '全国', '软件研发类', '硬件工程类', '产品类', '生产制造类', '财务类', '其他']::text[], true),
('华夏航空', '6.24', '其他', '27秋招正式批', '市场类（包含商分 战略）, 硬件工程类, 生产制造类, 职能类', '重庆', 'https://hxhk.zhiye.com/campus/jobs', null, null, array['其他', '27秋招正式批', '重庆', '市场类（包含商分', '战略）', '硬件工程类', '生产制造类', '职能类']::text[], true),
('海大集团', '6.24', '科技', '27秋招提前批', '管培生', '广州', 'https://haid1.zhiye.com/campus/detail?jobAdId=b5857a4d-11bb-499c-b392-02e736c86c42', null, null, array['科技', '27秋招提前批', '广州', '管培生']::text[], true),
('自变量机器人', '6.24', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '北京 深圳', 'https://x2-robot.jobs.feishu.cn/912130/position/list?keywords=&category=&location=&project=7650350869535869227&type=&job_hot_flag=&current=1&limit=10&functionCategory=&tag=', null, null, array['科技', '27秋招提前批', '北京', '深圳', '软件研发类', '硬件工程类']::text[], true),
('智元机器人（人才计划）', '6.24', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '北京 上海 深圳', 'https://mp.weixin.qq.com/s/YtVOtxKeyXX7IH6bL_4Y5A', null, null, array['科技', '27秋招提前批', '北京', '上海', '深圳', '软件研发类', '硬件工程类']::text[], true),
('德康集团', '6.11', '快消', '27秋招提前批', '管培生, 运营类, 市场类（包含商分 战略）, 职能类', '成都', 'https://hotjob.cn/wt/DeKang/web/index/webPositionN310!getOnePosition?postId=257501&recruitType=1&brandCode=1&importPost=0&columnId=1', null, null, array['快消', '27秋招提前批', '成都', '管培生', '运营类', '市场类（包含商分', '战略）', '职能类']::text[], true),
('它石智航（人才计划）', '6.23', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '上海', 'https://mp.weixin.qq.com/s/Fa164U5Atgslp3861-TGnQ?scene=1&click_id=484', null, null, array['科技', '27秋招提前批', '上海', '软件研发类', '硬件工程类']::text[], true),
('海信集团', '6.23', '央国企, 互联网', '27秋招提前批', '硬件工程类, 市场类（包含商分 战略）, 运营类, 产品类, 软件研发类, 销售类', '青岛', 'https://jobs.hisense.com/7/jobs', null, null, array['央国企', '互联网', '27秋招提前批', '青岛', '硬件工程类', '市场类（包含商分', '战略）', '运营类', '产品类', '软件研发类', '销售类']::text[], true),
('中车株洲电机', '6.23', '央国企', '27秋招提前批', '软件研发类, 硬件工程类, 生产制造类', '株洲', 'https://crrczzs.zhiye.com/campus', null, null, array['央国企', '27秋招提前批', '株洲', '软件研发类', '硬件工程类', '生产制造类']::text[], true),
('普渡机器人', '6.22', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 产品类, 销售类, 管培生', '深圳 成都', 'https://mp.weixin.qq.com/s/1QQ-g2lFxfiUh0Wv4sDo1Q', null, null, array['科技', '27秋招正式批', '深圳', '成都', '软件研发类', '硬件工程类', '产品类', '销售类', '管培生']::text[], true),
('BCG（中国）', '6.23', '外企, 金融', '27秋招正式批', '咨询, 其他', '北京 上海 香港 深圳 台北 海外', 'https://mp.weixin.qq.com/s/pG8ZfkWVigYQDxOcnTHsUg?scene=1&click_id=469', '中国区已开，海外base陆续启动', null, array['外企', '金融', '27秋招正式批', '北京', '上海', '香港', '深圳', '台北', '海外', '咨询', '其他']::text[], true),
('阿里巴巴（人才计划）', '6.23', '互联网', '27秋招提前批', '软件研发类', '北京 上海 杭州', 'https://mp.weixin.qq.com/s/5phiRqiTz7RqzGy8SDf3gg?scene=1&click_id=457', null, null, array['互联网', '27秋招提前批', '北京', '上海', '杭州', '软件研发类']::text[], true),
('拓竹科技', '6.23', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '上海 深圳', 'https://mp.weixin.qq.com/s/NRXtFGt3MXRKgs-zzZjFqg?scene=1&click_id=455', null, null, array['科技', '27秋招提前批', '上海', '深圳', '软件研发类', '硬件工程类']::text[], true),
('卓驭（人才计划）', '6.22', '科技', '27秋招提前批', '软件研发类', '上海 深圳', 'https://we.zyt.com/5/jobs?sessionid=', null, null, array['科技', '27秋招提前批', '上海', '深圳', '软件研发类']::text[], true),
('哔哩哔哩', '6.22', '互联网', '27秋招提前批', '软件研发类', '上海', 'https://jobs.bilibili.com/campus/positions?channel=bilibiliaccounts', null, null, array['互联网', '27秋招提前批', '上海', '软件研发类']::text[], true),
('四维图新', '6.17', '科技', '27秋招正式批', '硬件工程类, 市场类（包含商分 战略）, 产品类, 财务类', '北京 上海 安徽 合肥', 'https://navinfo102.zhiye.com/campus/jobs', null, null, array['科技', '27秋招正式批', '北京', '上海', '安徽', '合肥', '硬件工程类', '市场类（包含商分', '战略）', '产品类', '财务类']::text[], true),
('惠普', '6.16', '外企, 科技', '27秋招提前批', '市场类（包含商分 战略）, 运营类', '东京', 'https://apply.hp.com/careers?start=0&pid=41922401&sort_by=timestamp&filter_seniority=graduate', null, null, array['外企', '科技', '27秋招提前批', '东京', '市场类（包含商分', '战略）', '运营类']::text[], true),
('艾为电子', '5.14', '科技', '27秋招正式批', '硬件工程类', '哈尔滨 大连', 'https://awinic.zhiye.com/?sessionid=', null, null, array['科技', '27秋招正式批', '哈尔滨', '大连', '硬件工程类']::text[], true),
('库玛科技', '6.18', '科技', '27秋招提前批', '软件研发类', '深圳 成都', 'https://mammotion.jobs.feishu.cn/campus_recruitment/position/list?project=7611843487977654537', null, null, array['科技', '27秋招提前批', '深圳', '成都', '软件研发类']::text[], true),
('博世', '6.18', '外企', '27秋招正式批', '硬件工程类, 销售类', '北京 常州', 'https://app.mokahr.com/campus-recruitment/bosch/73873#/jobs?keyword=2027%E6%A0%A1%E6%8B%9B', null, null, array['外企', '27秋招正式批', '北京', '常州', '硬件工程类', '销售类']::text[], true),
('软通动力', '6.18', '科技', '27秋招正式批', '软件研发类, 硬件工程类', '全国', 'https://career.isoftstone.com/talent/htmls/xiaoyuanzhaopin/index.html', null, null, array['科技', '27秋招正式批', '全国', '软件研发类', '硬件工程类']::text[], true),
('基恩士', '6.18', '外企, 科技', '27秋招正式批', '销售类', '全国', 'https://www.keyence.com.cn/ss/careers/recruitment.jsp', null, null, array['外企', '科技', '27秋招正式批', '全国', '销售类']::text[], true),
('远景能源（部分）', '6.18', '科技', '27秋招提前批', '硬件工程类, 生产制造类', '全国', 'https://app.mokahr.com/campus-recruitment/envisiongroup/43123?sourceToken=4de642484982a5686fb4467b93436646#/jobs?department%5B0%5D=967570&department%5B1%5D=958964&page=1&project%5B0%5D=100124183&pageSize=30&anchorName=jobsList', null, null, array['科技', '27秋招提前批', '全国', '硬件工程类', '生产制造类']::text[], true),
('卓越教育', '6.18', '在线教育', '27秋招正式批', '教师', '广州 深圳 珠海 中山 佛山', 'https://wecruit.hotjob.cn/SU63366959bef57c270741e2c6/mc/position/campus?projectCode=102501', null, null, array['在线教育', '27秋招正式批', '广州', '深圳', '珠海', '中山', '佛山', '教师']::text[], true),
('北京飞机维修工程有限公司', '6.18', '央国企', '27秋招正式批', '硬件工程类', '全国', 'https://fjjwwx.zhiye.com/zpdetail/351577592', null, null, array['央国企', '27秋招正式批', '全国', '硬件工程类']::text[], true),
('豪迈集团', '6.18', '科技', '27秋招提前批', '硬件工程类, 生产制造类', '青岛 潍坊 日照', 'https://mp.weixin.qq.com/s/H_4EcBPvKVnChxidPNPOog', null, null, array['科技', '27秋招提前批', '青岛', '潍坊', '日照', '硬件工程类', '生产制造类']::text[], true),
('中国电科第十四研究所', '6.18', '央国企', '27秋招提前批', '软件研发类, 硬件工程类', '南京', 'https://mp.weixin.qq.com/s/lqZMq0oPNHeqasWwZY5Lgw?scene=1&click_id=423', null, null, array['央国企', '27秋招提前批', '南京', '软件研发类', '硬件工程类']::text[], true),
('协鑫集团', '6.18', '科技', '27秋招正式批', '硬件工程类, 市场类（包含商分 战略）, 运营类, 职能类', '苏州', 'https://app.mokahr.com/campus-recruitment/gclpower/166321#/jobs', null, null, array['科技', '27秋招正式批', '苏州', '硬件工程类', '市场类（包含商分', '战略）', '运营类', '职能类']::text[], true),
('中国电科第十研究所', '6.18', '央国企', '27秋招正式批', '软件研发类, 硬件工程类', '成都', 'https://cetc.iguopin.com/job-campus', null, null, array['央国企', '27秋招正式批', '成都', '软件研发类', '硬件工程类']::text[], true),
('云象机器人', '6.18', '科技', '27秋招正式批', '软件研发类, 生产制造类, 财务类, 销售类', '杭州', 'https://mp.weixin.qq.com/s/Y2WjDpk52xezGcrmgteqiQ?scene=1&click_id=400', null, null, array['科技', '27秋招正式批', '杭州', '软件研发类', '生产制造类', '财务类', '销售类']::text[], true),
('代塔供应链', '6.18', '科技', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 管培生, 职能类, 财务类, 人力类', '杭州 义乌 金华', 'https://mp.weixin.qq.com/s/oiuQlCDxIGovilgzjDlIqQ?scene=1&click_id=390', null, null, array['科技', '27秋招正式批', '杭州', '义乌', '金华', '软件研发类', '市场类（包含商分', '战略）', '管培生', '职能类', '财务类', '人力类']::text[], true),
('乐读', '6.18', '在线教育', '27秋招提前批', '教师', '全国', 'https://mp.weixin.qq.com/s/J2M6ogmIbLB23GhH0BhwCQ?scene=1&click_id=378', null, null, array['在线教育', '27秋招提前批', '全国', '教师']::text[], true),
('vivo（人才计划）', '6.17', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '广东', 'https://mp.weixin.qq.com/s/0KlCGXBMwxbU2NquqE6eQw?scene=1', '博士专项', null, array['科技', '27秋招提前批', '广东', '软件研发类', '硬件工程类']::text[], true),
('牧原', '6.17', '其他', '27秋招提前批', '硬件工程类, 产品类, 生产制造类, 管培生, 人力类, 财务类, 职能类', '全国', 'https://mp.weixin.qq.com/s/BKMC3SHRH65x48d6_CumaA?scene=1&click_id=366', '管培生前期都要进厂养猪，不是管培生的部分岗位也要；薪资整体都开的挺高的，管培非技术岗位能对标中大厂', null, array['其他', '27秋招提前批', '全国', '硬件工程类', '产品类', '生产制造类', '管培生', '人力类', '财务类', '职能类']::text[], true),
('晓禾教育', '6.17', '在线教育', '27秋招提前批', '教师', '武汉 郑州 襄阳 宜昌', 'https://jsj.top/f/r8j4Iz', null, null, array['在线教育', '27秋招提前批', '武汉', '郑州', '襄阳', '宜昌', '教师']::text[], true),
('龙蟠科技', '6.17', '科技', '27秋招提前批', '软件研发类, 市场类（包含商分 战略）, 人力类, 职能类, 财务类, 管培生', '南京', 'https://mp.weixin.qq.com/s/wdA3reFkAkCV3uuXWy0H1Q?scene=1', null, null, array['科技', '27秋招提前批', '南京', '软件研发类', '市场类（包含商分', '战略）', '人力类', '职能类', '财务类', '管培生']::text[], true),
('北京国望光学科技', '6.17', '央国企, 科技', '27秋招正式批', '软件研发类, 硬件工程类, 生产制造类', '北京', 'https://mp.weixin.qq.com/s/P7v0alwzLWnwD041R-Ipow?scene=1', null, null, array['央国企', '科技', '27秋招正式批', '北京', '软件研发类', '硬件工程类', '生产制造类']::text[], true),
('上海电气', '6.17', '央国企', '27秋招提前批', '硬件工程类', '上海', 'https://mp.weixin.qq.com/s/wKttLoGxZOWIA5Cr5vYfaA', null, null, array['央国企', '27秋招提前批', '上海', '硬件工程类']::text[], true),
('是为科技', '6.16', '科技', '27秋招正式批', '硬件工程类, 运营类, 管培生', '上海 南京 常州', 'https://mp.weixin.qq.com/s/OB_FDFcVt2LteSslt8w53g?scene=1&click_id=343', null, null, array['科技', '27秋招正式批', '上海', '南京', '常州', '硬件工程类', '运营类', '管培生']::text[], true),
('游族网络', '6.16', '互联网, 游戏', '27秋招正式批', '软件研发类, 产品类, 设计类, 销售类, 运营类', '上海', 'https://mp.weixin.qq.com/s/frovjpGTxw00M5mpeAN4VQ', null, null, array['互联网', '游戏', '27秋招正式批', '上海', '软件研发类', '产品类', '设计类', '销售类', '运营类']::text[], true),
('新东方（广东）', '6.16', '在线教育', '27秋招提前批', '运营类, 市场类（包含商分 战略）, 教师', '广州 深圳', 'https://mp.weixin.qq.com/s/oaBbzwfOjZ8maiTsDdur8A', null, null, array['在线教育', '27秋招提前批', '广州', '深圳', '运营类', '市场类（包含商分', '战略）', '教师']::text[], true),
('禾赛科技', '6.16', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 运营类, 生产制造类, 职能类', '上海 杭州', 'https://mp.weixin.qq.com/s/iiP1Ap4JW3i48TM9-se6Iw', null, null, array['科技', '27秋招提前批', '上海', '杭州', '软件研发类', '硬件工程类', '运营类', '生产制造类', '职能类']::text[], true),
('中电锦江', '6.16', '央国企', '27秋招提前批', '软件研发类, 硬件工程类', '成都', 'https://mp.weixin.qq.com/s/Vf_rAneDi62eISDVjnijkw?scene=1', null, null, array['央国企', '27秋招提前批', '成都', '软件研发类', '硬件工程类']::text[], true),
('米哈游（llm方向）', '6.16', '互联网, 游戏', '27秋招提前批', '软件研发类', '上海', 'https://jobs.mihoyo.com/#/campus/position/8785', null, null, array['互联网', '游戏', '27秋招提前批', '上海', '软件研发类']::text[], true),
('上海宇量昇', '6.16', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 生产制造类, 职能类', '上海', 'https://mp.weixin.qq.com/s/DnsN8K3oI2Xl5p_Lhj590A?scene=1&click_id=284', null, null, array['科技', '27秋招正式批', '上海', '软件研发类', '硬件工程类', '生产制造类', '职能类']::text[], true),
('中国电信（人才计划）', '6.16', '央国企', '27秋招提前批', '软件研发类, 硬件工程类', '北京 上海', 'https://mp.weixin.qq.com/s/IIK0IUVMBugNo1PcHu4F5g?scene=1&click_id=277', null, null, array['央国企', '27秋招提前批', '北京', '上海', '软件研发类', '硬件工程类']::text[], true),
('澜起科技', '6.15', '科技', '27秋招正式批', '硬件工程类, 产品类', '西安，南京，昆山', 'https://wxcc792e68420b3264.wx.moseeker.com/m/position/?wechat_signature=MTM4MTkwNTYzMzAyNDAyMDQ4MDg3MjEyMjfmvpzotbfnp5HmioA%3D', null, null, array['科技', '27秋招正式批', '西安', '南京', '昆山', '硬件工程类', '产品类']::text[], true),
('飞象星球', '6.15', '在线教育', '27秋招正式批', '软件研发类, 销售类', '北京', 'https://m.zhipin.com/mpa/html/weijd/weijd-job/e8591291ffb559620nF629m1GVFU?date8=20260615&sid=tosee_jd_f36112be243b62b20XJy3d-0GVVZ&openWeapp=1&fromSource=2', null, null, array['在线教育', '27秋招正式批', '北京', '软件研发类', '销售类']::text[], true),
('新东方(大连)', '6.15', '在线教育', '27秋招正式批', '教师', '大连', 'https://mp.weixin.qq.com/s/opE8PCABVFN5_FN-ndTkbw?scene=1&click_id=257', null, null, array['在线教育', '27秋招正式批', '大连', '教师']::text[], true),
('中铁设计集团', '6.15', '央国企', '27秋招正式批', '软件研发类, 硬件工程类, 生产制造类', '北京，济南，郑州，太原', 'https://mp.weixin.qq.com/s/AYkr0nHEyVkcatHBrLl8Ng?scene=1&click_id=252', null, null, array['央国企', '27秋招正式批', '北京', '济南', '郑州', '太原', '软件研发类', '硬件工程类', '生产制造类']::text[], true),
('铂力特', '6.15', '科技', '27秋招提前批', '硬件工程类', '西安', 'https://mp.weixin.qq.com/s/U5szidBAqLvrlgBKJX0t-g?scene=1', '6.27西安线下面试', null, array['科技', '27秋招提前批', '西安', '硬件工程类']::text[], true),
('科大讯飞（人才计划）', '6.14', '互联网', '27秋招正式批', '软件研发类', '北京 上海 合肥 西安 广州', 'https://mp.weixin.qq.com/s/vmh4sa_HA_0jJCq0nngJRA?scene=1&click_id=205', null, null, array['互联网', '27秋招正式批', '北京', '上海', '合肥', '西安', '广州', '软件研发类']::text[], true),
('安必平', '6.14', '其他', '27秋招正式批', '软件研发类, 销售类, 职能类', '广州', 'https://anbiping.jobs.feishu.cn/index/?keywords=&category=&location=&project=7639283695312554259&type=&job_hot_flag=&current=1&limit=10&functionCategory=&tag=', null, null, array['其他', '27秋招正式批', '广州', '软件研发类', '销售类', '职能类']::text[], true),
('中国科学院光电技术研究所', '6.12', '央国企', '27秋招提前批', '软件研发类, 硬件工程类, 生产制造类, 财务类', '成都', 'https://mp.weixin.qq.com/s/ZlSb1jOeyY6ld1NbQwbiZg', null, null, array['央国企', '27秋招提前批', '成都', '软件研发类', '硬件工程类', '生产制造类', '财务类']::text[], true),
('中国天楹', '6.12', '央国企', '27秋招正式批', '硬件工程类, 生产制造类, 人力类, 财务类', '南通', 'https://mp.weixin.qq.com/s/so7zsBb_A0Zy_Qo0VluIIQ', null, null, array['央国企', '27秋招正式批', '南通', '硬件工程类', '生产制造类', '人力类', '财务类']::text[], true),
('杰瑞集团', '6.12', '科技', '27秋招提前批', '硬件工程类, 销售类, 人力类, 财务类, 职能类', '北京，上海，深圳，广州，天津，烟台', 'https://future.jereh.com/campus/jobs?memory=%7B%7D&silence=1', null, null, array['科技', '27秋招提前批', '北京', '上海', '深圳', '广州', '天津', '烟台', '硬件工程类', '销售类', '人力类', '财务类', '职能类']::text[], true),
('航空工业通飞', '6.12', '央国企', '27秋招正式批', '硬件工程类, 设计类, 市场类（包含商分 战略）, 财务类, 产品类, 生产制造类', '全国', 'https://mp.weixin.qq.com/s/xEJCfP5Bl_kC-cQo84Gb_A', null, null, array['央国企', '27秋招正式批', '全国', '硬件工程类', '设计类', '市场类（包含商分', '战略）', '财务类', '产品类', '生产制造类']::text[], true),
('中国汽车技术研究中心', '6.12', '央国企', '27秋招提前批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 职能类, 管培生', '全国', 'https://mp.weixin.qq.com/s/6gFAYRnHtyiGKJqZkMSTqA', null, null, array['央国企', '27秋招提前批', '全国', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '职能类', '管培生']::text[], true),
('中国平安', '6.12', '央国企', '27秋招提前批', '软件研发类, 产品类, 市场类（包含商分 战略）', '全国', 'https://mp.weixin.qq.com/s/OGTRehNcDZgKaNosQ-aIvw', null, null, array['央国企', '27秋招提前批', '全国', '软件研发类', '产品类', '市场类（包含商分', '战略）']::text[], true),
('精进电动', '6.12', '科技, 制造业', '27秋招提前批', '硬件工程类, 生产制造类, 职能类', '北京，正定，菏泽', 'https://mp.weixin.qq.com/s/ixbn4WXqkjKj75m98ukvHA?scene=1&click_id=166', null, null, array['科技', '制造业', '27秋招提前批', '北京', '正定', '菏泽', '硬件工程类', '生产制造类', '职能类']::text[], true),
('mova', '6.12', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 设计类, 运营类, 产品类, 设计类, 职能类, 人力类', '苏州', 'https://mp.weixin.qq.com/s/mPJWt1MuoUOaduFKtVRIzg?scene=1&click_id=144', '追觅子品牌，内部算核心bu；打个小广告 内推码;IVHYTH.', null, array['科技', '27秋招正式批', '苏州', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '设计类', '运营类', '产品类', '职能类', '人力类']::text[], true),
('台达科技', '6.12', '科技', '27秋招提前批', '硬件工程类', '上海', 'https://mp.weixin.qq.com/s/1tLpOzqS9UJmZzRPmUbRTg', null, null, array['科技', '27秋招提前批', '上海', '硬件工程类']::text[], true),
('高途', '6.12', '在线教育', '27秋招提前批', '运营类, 销售类, 教师', '全国', 'https://app.mokahr.com/campus-recruitment/bjhl/102145#/', null, null, array['在线教育', '27秋招提前批', '全国', '运营类', '销售类', '教师']::text[], true),
('长江存储', '6.11', '央国企', '27秋招提前批', '软件研发类, 硬件工程类', '上海，北京，武汉', 'https://ymtc-campus.zhiye.com/campus/jobs', null, null, array['央国企', '27秋招提前批', '上海', '北京', '武汉', '软件研发类', '硬件工程类']::text[], true),
('中国航空无线电电子研究所', '6.11', '央国企', '27秋招提前批', '软件研发类, 硬件工程类, 生产制造类, 人力类', '上海，成都', 'https://mp.weixin.qq.com/s/XxwmAe5eJnlhYqP-O-YzWg', null, null, array['央国企', '27秋招提前批', '上海', '成都', '软件研发类', '硬件工程类', '生产制造类', '人力类']::text[], true),
('广州炫通电气科技', '6.11', '制造业', '27秋招正式批', '软件研发类, 硬件工程类, 生产制造类, 市场类（包含商分 战略）, 销售类', '广州', 'https://jsj.top/f/j3nhcX', null, null, array['制造业', '27秋招正式批', '广州', '软件研发类', '硬件工程类', '生产制造类', '市场类（包含商分', '战略）', '销售类']::text[], true),
('财通证券', '6.11', '央国企, 金融', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 运营类, 产品类, 销售类, 管培生, 财务类', '全国', 'https://mp.weixin.qq.com/s/2HSIy_5RJe-jzAHlXhJMIQ?scene=1&click_id=125', null, null, array['央国企', '金融', '27秋招正式批', '全国', '软件研发类', '市场类（包含商分', '战略）', '运营类', '产品类', '销售类', '管培生', '财务类']::text[], true),
('壹思唯国际教育', '6.10', '在线教育', '27秋招提前批', '运营类, 管培生, 财务类, 人力类', '北京，深圳', 'https://mp.weixin.qq.com/s/g9lozMZ7JEeL-Q0b5ve7ag', null, null, array['在线教育', '27秋招提前批', '北京', '深圳', '运营类', '管培生', '财务类', '人力类']::text[], true),
('海克斯康', '6.10', '科技, 制造业', '27秋招正式批', '硬件工程类, 生产制造类, 销售类', '深圳', 'https://mp.weixin.qq.com/s/FNaPSNAIEniKHP2mHTxGXg?scene=1&click_id=96', null, null, array['科技', '制造业', '27秋招正式批', '深圳', '硬件工程类', '生产制造类', '销售类']::text[], true),
('中铁四院', '6.9', '央国企', '27秋招提前批', '硬件工程类, 设计类', '全国', 'https://mp.weixin.qq.com/s/lsAOikuMkhpM7JQCfx3VKg?scene=1&click_id=254', null, null, array['央国企', '27秋招提前批', '全国', '硬件工程类', '设计类']::text[], true),
('南芯科技', '6.9', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 运营类, 产品类, 销售类, 生产制造类', '全国', 'https://nanxin.zhiye.com/campus/jobs', null, null, array['科技', '27秋招正式批', '全国', '软件研发类', '硬件工程类', '运营类', '产品类', '销售类', '生产制造类']::text[], true),
('中铁二院', '6.9', '央国企', '27秋招正式批', '软件研发类, 硬件工程类, 生产制造类, 设计类', '全国', 'https://mp.weixin.qq.com/s/dnmyS1l2IMaTqunbsISI2w?scene=1&click_id=73', null, null, array['央国企', '27秋招正式批', '全国', '软件研发类', '硬件工程类', '生产制造类', '设计类']::text[], true),
('中铁第四勘察设计院', '6.9', '央国企', '27秋招正式批', '硬件工程类, 财务类, 设计类', '全国', 'https://mp.weixin.qq.com/s/Sbd3pxyYVugQkfsIZvnOCw', null, null, array['央国企', '27秋招正式批', '全国', '硬件工程类', '财务类', '设计类']::text[], true),
('工大卫星', '6.9', '科技', '27秋招正式批', '硬件工程类, 生产制造类, 管培生', '北京，哈尔滨', 'https://mp.weixin.qq.com/s/KWBu6Bo_l1bAHRpwEfc_Nw?scene=1&click_id=56', null, null, array['科技', '27秋招正式批', '北京', '哈尔滨', '硬件工程类', '生产制造类', '管培生']::text[], true),
('江门金控', '6.9', '制造业', '27秋招正式批', '硬件工程类, 生产制造类', '江门', 'https://mp.weixin.qq.com/s/kjzMMCOo9aCYenu07M1uAg?scene=1&click_id=754', null, null, array['制造业', '27秋招正式批', '江门', '硬件工程类', '生产制造类']::text[], true),
('新意科技', '6.8', '科技', '27秋招提前批', '软件研发类', '福州', 'https://mp.weixin.qq.com/s/-QRqs07m4wEziNzdduNmNQ?scene=1&click_id=89', null, null, array['科技', '27秋招提前批', '福州', '软件研发类']::text[], true),
('星图测控', '6.8', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 销售类, 管培生', '合肥，西安', 'https://mp.weixin.qq.com/s/BIN95z6M_WQzbgy_esb05A?scene=1&click_id=57', null, null, array['科技', '27秋招正式批', '合肥', '西安', '软件研发类', '硬件工程类', '销售类', '管培生']::text[], true),
('群核科技（公众战略人才计划）', '6.8', '科技', '27秋招提前批', '市场类（包含商分 战略）', '杭州', 'https://app.mokahr.com/campus_apply/qunhemail/2832#/job/c204257b-1827-4874-8ba3-436334e4d21d', null, null, array['科技', '27秋招提前批', '杭州', '市场类（包含商分', '战略）']::text[], true),
('宇通集团', '6.8', '科技', '27秋招提前批', '市场类（包含商分 战略）, 生产制造类, 管培生, 人力类, 销售类', '郑州', 'https://mp.weixin.qq.com/s/3STvg5t6q9EDUieSj4bOTw', null, null, array['科技', '27秋招提前批', '郑州', '市场类（包含商分', '战略）', '生产制造类', '管培生', '人力类', '销售类']::text[], true),
('sharpa', '6.8', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 运营类, 市场类（包含商分 战略）, 产品类, 财务类, 职能类', '上海，新加坡', 'https://fcn5hvc5qbfs.jobs.feishu.cn/668262/?spread=A2B3G4G', null, null, array['科技', '27秋招提前批', '上海', '新加坡', '软件研发类', '硬件工程类', '运营类', '市场类（包含商分', '战略）', '产品类', '财务类', '职能类']::text[], true),
('雅培', '6.6', '外企', '27秋招提前批', '管培生', '上海，杭州，嘉兴', 'https://mp.weixin.qq.com/s/wNww_FO1CYkYZERncHyUVA', null, null, array['外企', '27秋招提前批', '上海', '杭州', '嘉兴', '管培生']::text[], true),
('进迭时空', '6.6', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 运营类', '上海 珠海', 'https://app.mokahr.com/m/campus-recruitment/space-t1/67916', null, null, array['科技', '27秋招正式批', '上海', '珠海', '软件研发类', '硬件工程类', '运营类']::text[], true),
('炬光科技', '6.5', '科技', '27秋招正式批', '硬件工程类, 生产制造类, 职能类', '西安，合肥，韶关，新加坡，瑞士，马来西亚，德国', 'https://mp.weixin.qq.com/s/OEoOL3-IJr9taIOUgD_dxA', null, null, array['科技', '27秋招正式批', '西安', '合肥', '韶关', '新加坡', '瑞士', '马来西亚', '德国', '硬件工程类', '生产制造类', '职能类']::text[], true),
('好未来', '6.5', '在线教育', '27秋招提前批', '软件研发类', '北京', 'https://app.mokahr.com/campus-recruitment/tal/95443?locale=zh-CN#/job/ca772f85-4a21-41bb-bd3f-2e1c57b65469', null, null, array['在线教育', '27秋招提前批', '北京', '软件研发类']::text[], true),
('东芯半导体', '6.5', '科技', '27秋招正式批', '硬件工程类', '上海', 'https://mp.weixin.qq.com/s/3Jh5YexL980PlyjgZWy6mg?scene=1&click_id=90', null, null, array['科技', '27秋招正式批', '上海', '硬件工程类']::text[], true),
('小米（人才计划）', '6.5', '互联网', '27秋招正式批', '软件研发类, 硬件工程类', '北京，上海，深圳，武汉，南京', 'https://hr.xiaomi.com/toptalent?sessionid=', null, null, array['互联网', '27秋招正式批', '北京', '上海', '深圳', '武汉', '南京', '软件研发类', '硬件工程类']::text[], true),
('格见半导体', '6.4', '科技, 制造业', '27秋招正式批', '生产制造类, 管培生', '上海，深圳，成都，西安', 'https://gejian-semi.zhiye.com/', null, null, array['科技', '制造业', '27秋招正式批', '上海', '深圳', '成都', '西安', '生产制造类', '管培生']::text[], true),
('乾元实验室', '6.4', '央国企', '27秋招正式批', null, '杭州', 'https://mp.weixin.qq.com/s/uDdTTk0ES_QEF1G4JZpUnA', null, null, array['央国企', '27秋招正式批', '杭州']::text[], true),
('美团（人才计划）', '6.3', '互联网', '27秋招正式批', '软件研发类', '北京，上海，深圳，成都', 'https://mp.weixin.qq.com/s/g-8j7uMH3FSWdrVLiJ5fXQ', null, null, array['互联网', '27秋招正式批', '北京', '上海', '深圳', '成都', '软件研发类']::text[], true),
('金凤科技', '6.3', '制造业', '27秋招提前批', '生产制造类', '内蒙古', 'https://goldwind2.zhiye.com/campus/jobs', null, null, array['制造业', '27秋招提前批', '内蒙古', '生产制造类']::text[], true),
('碧桂园', '6.2', '其他', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 运营类, 产品类, 人力类, 财务类', '佛山', 'https://app.mokahr.com/campus-recruitment/bgyfw/47073#/jobs?project=100130055', null, null, array['其他', '27秋招正式批', '佛山', '软件研发类', '市场类（包含商分', '战略）', '运营类', '产品类', '人力类', '财务类']::text[], true),
('Meshy', '6.2', '互联网, 外企', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 运营类, 产品类, 销售类', '北京，上海，深圳', 'https://app.mokahr.com/social-recruitment/taichi/148086?locale=en-US#/', '全栈实际上就是修bug', null, array['互联网', '外企', '27秋招正式批', '北京', '上海', '深圳', '软件研发类', '市场类（包含商分', '战略）', '运营类', '产品类', '销售类']::text[], true),
('顺纺集团', '6.2', '制造业', '27秋招提前批', '生产制造类, 销售类', '贵阳，广东，湖北', 'https://mp.weixin.qq.com/s/PBAItWKL4fouCpxOxbcl1A', null, null, array['制造业', '27秋招提前批', '贵阳', '广东', '湖北', '生产制造类', '销售类']::text[], true),
('哈银消费金融', '6.1', '央国企, 金融', '27秋招提前批', '软件研发类, 市场类（包含商分 战略）', '北京，哈尔滨', 'https://hrbbcf1.zhiye.com/campus/jobs?queryId=607b901e-01b4-4fb4-b284-28f670aeadde', null, null, array['央国企', '金融', '27秋招提前批', '北京', '哈尔滨', '软件研发类', '市场类（包含商分', '战略）']::text[], true),
('双胞胎集团', '6.1', '其他', '27秋招正式批', '市场类（包含商分 战略）, 生产制造类', '全国', 'https://wecruit.hotjob.cn/SU69f82a62e791100f0af4d1ea/mc/position/campus?projectCode=101701&showProjectBanner=true', null, null, array['其他', '27秋招正式批', '全国', '市场类（包含商分', '战略）', '生产制造类']::text[], true),
('长鑫存储', '5.30', '科技', '27秋招提前批', '硬件工程类', '北京，上海，合肥，西安', 'https://cxmt.zhiye.com/campus/jobs', null, null, array['科技', '27秋招提前批', '北京', '上海', '合肥', '西安', '硬件工程类']::text[], true),
('时代上汽', '5.30', '制造业', '27秋招正式批', '生产制造类', '常州', 'https://mp.weixin.qq.com/s/2BqIGzcI4EX_pmvxUoqT3Q?scene=1&click_id=227', null, null, array['制造业', '27秋招正式批', '常州', '生产制造类']::text[], true),
('渝欧数智', '5.29', '互联网', '27秋招提前批', '运营类', '重庆', 'https://tcnrm7b535t2.jobs.feishu.cn/748205/position/list?spread=NYFMABD', null, null, array['互联网', '27秋招提前批', '重庆', '运营类']::text[], true),
('快手（人才计划）', '5.28', '互联网', '27秋招正式批', '软件研发类', '北京，上海，杭州，深圳', 'https://mp.weixinbridge.com/mp/wapredirect?url=https%3A%2F%2Fcampus.kuaishou.cn%2Frecruit%2Fcampus%2Fe%2F%23%2Fcampus%2Fjobs%3FpageNum%3D1%26positionLabel%3Dkstar%26positionNatureCode%3Dfulltime&action=appmsg_redirect&uin=MTI5MDc5NTgwMQ%3D%3D&biz=MzI5MTk3OTM1Nw==&mid=2247500335&idx=1&type=2&scene=0', null, null, array['互联网', '27秋招正式批', '北京', '上海', '杭州', '深圳', '软件研发类']::text[], true),
('TP-LINK', '5.28', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '北京，杭州，深圳，南京', 'https://hr.tp-link.com.cn/?sessionid=', null, null, array['科技', '27秋招提前批', '北京', '杭州', '深圳', '南京', '软件研发类', '硬件工程类']::text[], true),
('知乎', '5.27', '互联网', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 产品类, 运营类', '北京', 'https://app.mokahr.com/campus_apply/zhihu/68321#/jobs?zhineng%5B0%5D=131503&page=1&_k=1ggyui', null, null, array['互联网', '27秋招正式批', '北京', '软件研发类', '市场类（包含商分', '战略）', '产品类', '运营类']::text[], true),
('会世资产', '5.25', '金融', '27秋招正式批', '软件研发类', '上海', 'https://mp.weixin.qq.com/s/491fgQagZgCbTiQjxSsyyA?scene=1&click_id=231', null, null, array['金融', '27秋招正式批', '上海', '软件研发类']::text[], true),
('歌尔股份', '5.27', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 销售类', '全国 海外', 'https://wecruit.hotjob.cn/SU63c50f8b0dcad47488052192/mc/position/campus?projectCode=106001&showProjectBanner=true', null, null, array['科技', '27秋招提前批', '全国', '海外', '软件研发类', '硬件工程类', '销售类']::text[], true),
('三环集团', '5.25', '科技', '27秋招提前批', '硬件工程类', '四川，江苏，广州，深圳，泰国', 'https://hr.cctc.cc/school', null, null, array['科技', '27秋招提前批', '四川', '江苏', '广州', '深圳', '泰国', '硬件工程类']::text[], true),
('海信集团', '5.25', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 产品类, 运营类', '全国', 'https://jobs.hisense.com/7/jobs', null, null, array['科技', '27秋招提前批', '全国', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '产品类', '运营类']::text[], true),
('云深处科技', '5.24', '科技', '27秋招正式批', '软件研发类, 销售类', '北京，杭州', 'https://app135149.dingtalkoxm.com/campus-recruitment/yunshenchu/100000136?locale=zh-CN#/', null, null, array['科技', '27秋招正式批', '北京', '杭州', '软件研发类', '销售类']::text[], true),
('懂车帝', '5.21', '互联网', '27秋招提前批', '软件研发类, 市场类（包含商分 战略）, 运营类, 产品类, 销售类', '北京，上海，杭州，重庆，合肥，武汉', 'https://dcar.jobs.feishu.cn/campus/?sessionid=', null, null, array['互联网', '27秋招提前批', '北京', '上海', '杭州', '重庆', '合肥', '武汉', '软件研发类', '市场类（包含商分', '战略）', '运营类', '产品类', '销售类']::text[], true),
('韶音科技', '5.20', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 产品类', '深圳', 'https://app.mokahr.com/campus-recruitment/aftershokzhr/36940?sessionid=#/page/%E6%A0%A1%E5%9B%AD%E6%8B%9B%E8%81%98', null, null, array['科技', '27秋招提前批', '深圳', '软件研发类', '硬件工程类', '产品类']::text[], true),
('上海建科咨询集团', '5.19', '央国企', '27秋招提前批', '硬件工程类, 职能类', '上海', 'https://mp.weixin.qq.com/s/y9lqm3_8FhBnw2x5qKuPGA?scene=1&click_id=229', null, null, array['央国企', '27秋招提前批', '上海', '硬件工程类', '职能类']::text[], true),
('百度', '5.18', '互联网', '27秋招提前批', '软件研发类', '北京，上海，深圳', 'https://talent.baidu.com/jobs/list', null, null, array['互联网', '27秋招提前批', '北京', '上海', '深圳', '软件研发类']::text[], true),
('蚂蚁集团', '5.18', '互联网', '27秋招提前批', '软件研发类', '北京 杭州', 'https://hrrecommend.antgroup.com/job-list.html?code=RI2D8Qo_53mjwttzQKtL6z1ZIgy8ysp5ZdhFF3N6Hoo%3D', null, null, array['互联网', '27秋招提前批', '北京', '杭州', '软件研发类']::text[], true),
('三未信安', '5.15', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '济南', 'https://sansec.zhiye.com/campus', null, null, array['科技', '27秋招提前批', '济南', '软件研发类', '硬件工程类']::text[], true),
('汉缆股份', '5.14', '制造业', '27秋招提前批', '生产制造类, 销售类', '青岛', 'https://mp.weixin.qq.com/s/ku_5567zMLM_HkSUG6xYcg?scene=1&click_id=173', null, null, array['制造业', '27秋招提前批', '青岛', '生产制造类', '销售类']::text[], true),
('卫宁健康', '5.13', '科技', '27秋招正式批', '软件研发类, 产品类, 运营类, 销售类', '安徽', 'https://mp.weixin.qq.com/s/ulfbeXte8r2KHogOpBTN7g?scene=1&click_id=47', null, null, array['科技', '27秋招正式批', '安徽', '软件研发类', '产品类', '运营类', '销售类']::text[], true),
('凯捷中国', '5.8', '科技, 外企', '27秋招提前批', '软件研发类, 市场类（包含商分 战略）, 运营类', '北京，上海，大连，沈阳', 'https://v.wjx.cn/vm/ryU3Kv3.aspx', null, null, array['科技', '外企', '27秋招提前批', '北京', '上海', '大连', '沈阳', '软件研发类', '市场类（包含商分', '战略）', '运营类']::text[], true),
('航天一院', '5.8', '央国企', '27秋招提前批', '硬件工程类', '北京', 'https://m.zhaopin.com/xiaoyuan/company/detail?number=KA0133192447P90000003000&srccode=644201', null, null, array['央国企', '27秋招提前批', '北京', '硬件工程类']::text[], true),
('索迪斯', '5.8', '外企', '27秋招提前批', '管培生', '全国', 'https://mp.weixin.qq.com/s/-V8jae9KwOy0xv9NfURBvw', null, null, array['外企', '27秋招提前批', '全国', '管培生']::text[], true),
('宇树科技', '5.2', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）, 设计类, 职能类', '北京，上海，杭州，海外', 'https://unitree.zhiye.com/', null, null, array['科技', '27秋招正式批', '北京', '上海', '杭州', '海外', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）', '设计类', '职能类']::text[], true),
('三一集团', '4.24', '科技', '27秋招提前批', '软件研发类, 硬件工程类', '全国', 'https://sany.zhiye.com/campus/jobs?LocId=%5B%7B%22id%22%3A%221100%22%2C%22label%22%3A%22%E5%8C%97%E4%BA%AC%E5%B8%82%22%7D%5D', null, null, array['科技', '27秋招提前批', '全国', '软件研发类', '硬件工程类']::text[], true),
('海尔智家', '4.20', '科技', '27秋招提前批', '软件研发类, 硬件工程类, 市场类（包含商分 战略）', '全国 海外', 'https://maker.haier.net/client/campusmobile/customizedjobs/type/top.html?sessionid=', null, null, array['科技', '27秋招提前批', '全国', '海外', '软件研发类', '硬件工程类', '市场类（包含商分', '战略）']::text[], true),
('方田教育', '4.12', '在线教育', '27秋招提前批', '教师', '新加坡，合肥，上海，南京等', 'https://mp.weixin.qq.com/s/Bz4HcWYod7vs4KVqI5wAxw?scene=1&click_id=213', null, null, array['在线教育', '27秋招提前批', '新加坡', '合肥', '上海', '南京等', '教师']::text[], true),
('思榕智能装备', '4.2', '科技', '27秋招正式批', '软件研发类, 硬件工程类, 管培生, 人力类, 财务类', '昆山 东苑', 'https://strongtc.zhiye.com/jobs?queryId=75092bc2-808e-4daa-a74d-aafba907f736&memory=%7B%7D&silence=1', null, null, array['科技', '27秋招正式批', '昆山', '东苑', '软件研发类', '硬件工程类', '管培生', '人力类', '财务类']::text[], true),
('华泰证券', '3.31', '金融', '27秋招正式批', '软件研发类, 市场类（包含商分 战略）, 咨询, 其他', '北京 上海 南京 深圳', 'https://mp.weixin.qq.com/s/P5QucGx1wkPbgrXec7OXyQ', null, null, array['金融', '27秋招正式批', '北京', '上海', '南京', '深圳', '软件研发类', '市场类（包含商分', '战略）', '咨询', '其他']::text[], true),
('嘉实基金', '3.13', '金融', '27秋招正式批', '市场类（包含商分 战略）, 运营类, 产品类, 销售类, 咨询', '北京', 'https://app.mokahr.com/campus-recruitment/jsfund/43906#/jobs/', null, null, array['金融', '27秋招正式批', '北京', '市场类（包含商分', '战略）', '运营类', '产品类', '销售类', '咨询']::text[], true)
) as incoming (
  company_name,
  start_date,
  industry,
  batch_type,
  job_titles,
  locations,
  apply_url,
  notes,
  logo_url,
  tags,
  is_active
)
where not exists (
  select 1
  from public.jobs existing
  where existing.company_name = incoming.company_name
    and existing.apply_url = incoming.apply_url
);
