#!/usr/bin/env python3
"""Build deterministic StarJob resume common-font subsets and TS coverage data."""

from __future__ import annotations

from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "public" / "fonts" / "resume"
GENERATED_COVERAGE = ROOT / "src" / "generated" / "resumeFontCommonCoverage.ts"

FONT_PAIRS = (
    (FONT_DIR / "NotoSerifSC-Regular-full-v1.ttf", FONT_DIR / "NotoSerifSC-Regular-common-v1.ttf"),
    (FONT_DIR / "NotoSerifSC-Bold-full-v1.ttf", FONT_DIR / "NotoSerifSC-Bold-common-v1.ttf"),
)

RESUME_TEXT = """
姓名 Your Name 个人网站 LinkedIn GitHub Website
教育背景 实习经历 项目经历 校园经历 获奖经历 证书 技能 兴趣 自定义模块
公司名称 岗位名称 项目名称 学校 核心课程 荣誉奖项 语言 至今
EDUCATION EXPERIENCE PROJECTS ACTIVITIES HONORS AWARDS CERTIFICATIONS SKILLS ADDITIONAL
Company Position Project School Relevant Coursework Honors Languages Present Skills
示例简历 产品经理实习生 互联网产品方向 王小星 上海 复旦大学 本科 信息管理与信息系统
数据结构 数据库系统 用户研究 商业分析 校级一等奖学金 优秀学生干部 欧莱雅中国
秋招岗位信息管理 需求梳理 用户反馈 迭代清单 岗位筛选 投递状态 看板 测试用户
商业创新挑战赛 团队产品负责人 年轻消费者 可持续美妆 访谈 竞品分析 核心使用场景
产品概念 商业模式 产品原型设计 市场进入策略 英文路演 材料 产品与数据
用户访谈 SQL Figma Excel 学生会 外联部 企业交流 全国大学生市场调研大赛
语言能力 英语 资料阅读 双语沟通
求职 应聘 目标 职位 职业 意向 专业 学历 学位 硕士 博士 研究生 毕业 院校 学院
成绩 排名 奖学金 课程 研究 论文 专利 课题 实验 分析 建模 算法 开发 测试 运营 市场
咨询 投研 金融 会计 审计 法务 人力资源 行政 销售 客户 服务 供应链 采购 制造 工程
软件 硬件 前端 后端 全栈 数据 人工智能 机器学习 深度学习 产品 设计 交互 视觉 品牌
负责 参与 主导 协助 完成 推进 优化 搭建 设计 实现 提升 降低 增长 转化 效率 质量
团队 部门 公司 集团 有限公司 大学 科技 网络 信息 管理 系统 项目 活动 比赛 实践
联系方式 手机 电话 邮箱 地址 城市 微信 主页 链接 作品集 个人简介 自我评价
熟练 掌握 了解 精通 能力 经验 技能 工具 编程语言 框架 数据库 平台
年月日 北京 上海 天津 重庆 广州 深圳 杭州 南京 苏州 成都 武汉 西安 香港 澳门
"""

EXTRA_PUNCTUATION = "，。！？；：、（）【】《》〈〉“”‘’—…·￥％＃＠＆＋－＝／｜＿～「」『』〔〕［］｛｝•"


def gb2312_level_one() -> set[str]:
    characters: set[str] = set()
    for zone in range(16, 56):
        for position in range(1, 95):
            encoded = bytes((zone + 0xA0, position + 0xA0))
            try:
                characters.add(encoded.decode("gb2312"))
            except UnicodeDecodeError:
                continue
    return characters


def build_charset() -> set[int]:
    characters = {chr(codepoint) for codepoint in range(0x20, 0x7F)}
    characters.update("\n\r\t")
    characters.update(EXTRA_PUNCTUATION)
    characters.update(RESUME_TEXT)
    characters.update(gb2312_level_one())
    return {ord(character) for character in characters}


def subset_font(source: Path, destination: Path, unicodes: set[int]) -> None:
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_legacy = True
    options.name_languages = ["*"]
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    options.recalc_average_width = True
    options.recalc_timestamp = False
    options.canonical_order = True

    font = subset.load_font(str(source), options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)
    subset.save_font(font, str(destination), options)

    with TTFont(destination, lazy=False, recalcTimestamp=False) as generated:
        if "cmap" not in generated or not generated.getBestCmap():
            raise RuntimeError(f"Generated font has no usable cmap: {destination}")


def codepoint_ranges(unicodes: set[int]) -> list[tuple[int, int]]:
    points = sorted(unicodes)
    ranges: list[tuple[int, int]] = []
    start = previous = points[0]
    for point in points[1:]:
        if point == previous + 1:
            previous = point
            continue
        ranges.append((start, previous))
        start = previous = point
    ranges.append((start, previous))
    return ranges


def write_coverage(unicodes: set[int]) -> None:
    ranges = codepoint_ranges(unicodes)
    lines = [
        "// Generated by scripts/build_resume_font_subset.py. Do not edit by hand.",
        f"export const RESUME_FONT_COMMON_CODEPOINT_COUNT = {len(unicodes)};",
        "export const RESUME_FONT_COMMON_RANGES: ReadonlyArray<readonly [number, number]> = [",
    ]
    lines.extend(f"  [0x{start:X}, 0x{end:X}]," for start, end in ranges)
    lines.extend(["] as const;", ""])
    GENERATED_COVERAGE.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_COVERAGE.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    unicodes = build_charset()
    print(f"Common character count: {len(unicodes)}")
    for source, destination in FONT_PAIRS:
        if not source.exists():
            raise FileNotFoundError(f"Missing source font: {source}")
        subset_font(source, destination, unicodes)
        print(f"{source.name}: {source.stat().st_size} -> {destination.name}: {destination.stat().st_size} bytes")
    write_coverage(unicodes)
    print(f"Coverage data: {GENERATED_COVERAGE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
