begin;

create table if not exists public.extension_autofill_rate_operations (
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_id uuid not null,
  batch_count smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, operation_id)
);

alter table public.extension_autofill_rate_operations
  drop constraint if exists extension_autofill_rate_operations_batch_count_check;

alter table public.extension_autofill_rate_operations
  add constraint extension_autofill_rate_operations_batch_count_check
  check (batch_count between 1 and 15);

create index if not exists extension_autofill_rate_operations_created_idx
  on public.extension_autofill_rate_operations (created_at);

create index if not exists extension_autofill_rate_operations_user_updated_idx
  on public.extension_autofill_rate_operations (user_id, updated_at);

alter table public.extension_autofill_rate_operations enable row level security;

create table if not exists public.extension_autofill_rate_batches (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  operation_id uuid not null,
  created_at timestamptz not null default now(),
  foreign key (user_id, operation_id)
    references public.extension_autofill_rate_operations (user_id, operation_id)
    on delete cascade
);

create index if not exists extension_autofill_rate_batches_user_created_idx
  on public.extension_autofill_rate_batches (user_id, created_at);

alter table public.extension_autofill_rate_batches enable row level security;

create or replace function public.take_extension_autofill_rate_slot(
  p_user_id uuid,
  p_operation_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_batch_count smallint;
  active_operation_count integer;
  active_batch_count integer;
  operation_exists boolean;
  operation_active boolean;
begin
  if p_user_id is null or p_operation_id is null then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  -- A separate timestamped row for every accepted model batch is required for
  -- a true rolling window. Counting only operation.created_at would allow an
  -- operation started just before the boundary to escape the 15-batch limit.
  delete from public.extension_autofill_rate_batches
  where user_id = p_user_id
    and created_at < now() - interval '10 minutes';

  -- Operation ids are unique per user action. Retain completed counters well
  -- beyond the live window, then remove only dormant rows with no batch event
  -- so long-term use does not grow the operation table without bound.
  delete from public.extension_autofill_rate_operations as operation
  where operation.user_id = p_user_id
    and operation.updated_at < now() - interval '7 days'
    and not exists (
      select 1
      from public.extension_autofill_rate_batches as batch
      where batch.user_id = operation.user_id
        and batch.operation_id = operation.operation_id
    );

  select batch_count into current_batch_count
  from public.extension_autofill_rate_operations
  where user_id = p_user_id
    and operation_id = p_operation_id
  for update;
  operation_exists := found;

  select count(distinct operation_id)::integer, count(*)::integer
  into active_operation_count, active_batch_count
  from public.extension_autofill_rate_batches
  where user_id = p_user_id
    and created_at >= now() - interval '10 minutes';

  select exists (
    select 1
    from public.extension_autofill_rate_batches
    where user_id = p_user_id
      and operation_id = p_operation_id
      and created_at >= now() - interval '10 minutes'
  ) into operation_active;

  if operation_exists then
    -- The advisory lock serializes Promise.all batches for one user: batch 15
    -- is accepted from a count of 14, while batch 16 observes 15 and fails.
    if current_batch_count >= 15
      or active_batch_count >= 15
      or (not operation_active and active_operation_count >= 5) then
      return false;
    end if;

    update public.extension_autofill_rate_operations
    set batch_count = batch_count + 1,
        updated_at = now()
    where user_id = p_user_id
      and operation_id = p_operation_id;

    insert into public.extension_autofill_rate_batches (user_id, operation_id)
    values (p_user_id, p_operation_id);
    return true;
  end if;

  if active_operation_count >= 5 or active_batch_count >= 15 then
    return false;
  end if;

  insert into public.extension_autofill_rate_operations (
    user_id,
    operation_id,
    batch_count
  ) values (
    p_user_id,
    p_operation_id,
    1
  );

  insert into public.extension_autofill_rate_batches (user_id, operation_id)
  values (p_user_id, p_operation_id);
  return true;
end;
$$;

revoke all on table public.extension_autofill_rate_operations from public, anon, authenticated;
grant select, insert, update, delete on table public.extension_autofill_rate_operations to service_role;
revoke all on table public.extension_autofill_rate_batches from public, anon, authenticated;
grant select, insert, update, delete on table public.extension_autofill_rate_batches to service_role;
revoke all on function public.take_extension_autofill_rate_slot(uuid, uuid) from public, anon, authenticated;
grant execute on function public.take_extension_autofill_rate_slot(uuid, uuid) to service_role;

commit;
